project:
  type: website
  output-dir: docs

website:
  title: "Lisa Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects and Publications
      - href: Resume_Spring 2025

format:
  html:
    theme: trestles
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
